return {
  DiffAdd = {
    bg = "#253B22",
    ctermbg = 22,
    ctermfg = 15,
    fg = "#F8F8F8",
  },
  DiffChange = {
    bg = "#420E09",
    ctermbg = 52,
    ctermfg = 185,
    fg = "#E6DB74",
  },
  DiffDelete = {
    bg = "#420E09",
    ctermbg = 52,
    ctermfg = 197,
    fg = "#F92672",
  },
  DiffText = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 95,
    fg = "#75715E",
  },
  Ignore = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = "NONE",
    fg = "NONE",
  },
  PmenuSBar = {
    bg = "#334455",
    ctermbg = 59,
    ctermfg = 81,
    fg = "#66D9EF",
  },
  PmenuSet = {
    bg = "#000000",
    ctermbg = 233,
    ctermfg = 81,
    fg = "#66D9EF",
  },
  PreCondit = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  Preproc = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  SpecialComment = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  TabLine = {
    bg = "#000000",
    ctermbg = 233,
    ctermfg = 102,
    fg = "#8F908A",
  },
  TabLineFill = {
    bg = "#111111",
    ctermbg = 233,
    ctermfg = 233,
    fg = "#000000",
  },
  TabLineSel = {
    bg = "#334455",
    ctermbg = 59,
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  TermCursor = {
    bg = "#F8F8F2",
    ctermbg = 15,
    ctermfg = 233,
    fg = "#000000",
  },
  TermCursorNC = {
    bg = "#778899",
    ctermbg = 103,
    ctermfg = 233,
    fg = "#000000",
  },
  TypeDef = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  Underlined = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  VertSplit = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 95,
    fg = "#75715E",
  },
  cppModifier = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  cppSTLnamespace = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  cppSTLtype = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  javaScriptArrowFunction = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  javaScriptFunctionCallWithArgs = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  javaScriptFunctionCallWithoutArgs = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  javaScriptMethodCallWithArgs = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  javaScriptMethodCallWithoutArgs = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  javaScriptStaticFunctionWithArgs = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  javaScriptStaticFunctionWithoutArgs = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  jsArgsObj = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsArrowFunction = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsAsyncKeyword = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsBlockComment = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 67,
    fg = "#5F87AF",
    italic = true,
  },
  jsBooleanFalse = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  jsBooleanTrue = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  jsBuiltins = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsClass = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsComment = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 67,
    fg = "#5F87AF",
    italic = true,
  },
  jsCommentTodo = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 103,
    fg = "#778899",
  },
  jsConditional = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsCvsTag = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 67,
    fg = "#5F87AF",
    italic = true,
  },
  jsDecorator = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  jsDecoratorFunction = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  jsDocParam = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 103,
    fg = "#778899",
  },
  jsDocSeeTag = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 103,
    fg = "#778899",
  },
  jsDocTags = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 103,
    fg = "#778899",
  },
  jsDocType = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 103,
    fg = "#778899",
  },
  jsDocTypeNoParam = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 103,
    fg = "#778899",
  },
  jsEnvComment = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 67,
    fg = "#5F87AF",
    italic = true,
  },
  jsExceptions = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsExportContainer = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsFloat = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  jsFuncArgRest = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsFuncArgs = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 208,
    fg = "#FD971F",
  },
  jsFuncCall = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  jsFuncName = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  jsFunctionKey = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  jsFutureKeys = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsGenerator = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsGlobalNodeObjects = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
    italic = true,
  },
  jsGlobalObjects = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsHtmlEvents = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsImportContainer = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsKeyword = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsLabel = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsLineComment = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 67,
    fg = "#5F87AF",
    italic = true,
  },
  jsModuleWords = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsModules = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsNumber = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  jsObjectKey = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsOf = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsOperator = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsRegexpBackRef = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpBoundary = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpCharClass = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpGroup = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpMod = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpOr = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpQuantifier = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpSpecial = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRegexpString = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsRepeat = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsStatement = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsStorageClass = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  jsStringD = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsStringS = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsTaggedTemplate = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsTemplateBraces = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  jsTemplateString = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsTemplateVar = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  jsTernaryIfOperator = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  jsThis = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
    italic = true,
  },
  jsonBraces = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  jsonKeyword = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  jsonNull = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  jsonPadding = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  purescriptConstructor = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  purescriptConstructorDecl = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  purescriptData = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  purescriptDelimiter = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  purescriptImportKeyword = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  purescriptModuleKeyword = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  purescriptTypeAlias = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  purescriptTypeVar = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  purescriptWhere = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
}
