return {
  ColorColumn = {
    bg = "#383A3E",
    ctermbg = 236,
    ctermfg = "NONE",
    fg = "NONE",
    sp = "none",
  },
  Comment = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 67,
    fg = "#5F87AF",
    italic = true,
  },
  Conceal = {
    bg = "#000000",
    ctermbg = 233,
    ctermfg = 81,
    fg = "#66D9EF",
  },
  Cursor = {
    bg = "#F8F8F2",
    ctermbg = 15,
    ctermfg = 233,
    fg = "#000000",
  },
  CursorColumn = {
    bg = "#383A3E",
    ctermbg = 236,
    ctermfg = "NONE",
    fg = "NONE",
    sp = "none",
  },
  CursorLine = {
    bg = "#383A3E",
    ctermbg = 236,
    ctermfg = "NONE",
    fg = "NONE",
    sp = "none",
  },
  Directory = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  Error = {
    bg = "#960020",
    ctermbg = 88,
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  ErrorMsg = {
    bg = "#F92672",
    ctermbg = 197,
    ctermfg = 233,
    fg = "#000000",
  },
  FoldColumn = {
    bg = "#211F1C",
    ctermbg = 0,
    ctermfg = "NONE",
    fg = "NONE",
  },
  Folded = {
    bg = "#211F1C",
    ctermbg = 0,
    ctermfg = 103,
    fg = "#778899",
  },
  LineNr = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 102,
    fg = "#8F908A",
  },
  Macro = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  MatchParen = {
    bg = "#333333",
    bold = true,
    ctermbg = "NONE",
    ctermfg = 203,
    fg = "#f43753",
    link = "MatchWord",
  },
  ModeMsg = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  MoreMsg = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  NonText = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 59,
    fg = "#49483E",
  },
  Normal = {
    bg = "#000000",
    ctermbg = 233,
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  Pmenu = {
    bg = "#223344",
    ctermbg = 23,
    ctermfg = 15,
    fg = "#F8F8F8",
  },
  PmenuSel = {
    bg = "#334455",
    ctermbg = 59,
    ctermfg = 81,
    fg = "#66D9EF",
  },
  PmenuThumb = {
    bg = "#778899",
    ctermbg = 103,
    ctermfg = 103,
    fg = "#778899",
  },
  Question = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  Search = {
    bg = "#FFE972",
    ctermbg = 221,
    ctermfg = 0,
    fg = "#000000",
  },
  SignColumn = {
    bg = "#211F1C",
    ctermbg = 0,
    ctermfg = "NONE",
    fg = "NONE",
    sp = "NONE",
  },
  SpecialKey = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 59,
    fg = "#49483E",
  },
  Title = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
    sp = "none",
  },
  Visual = {
    bg = "#49483E",
    ctermbg = 59,
    ctermfg = "NONE",
    fg = "NONE",
  },
  WarningMsg = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92672",
  },
  Boolean = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  Character = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
  },
  Constant = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  Define = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
    sp = "none",
  },
  Delimiter = {
    bg = "NONE",
    bold = true,
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  Float = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  Function = {
    bg = "NONE",
    bold = true,
    ctermbg = "NONE",
    ctermfg = 112,
    fg = "#A6E22E",
  },
  Identifier = {
    bg = "NONE",
    bold = true,
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#ca2168",
    sp = "none",
  },
  Include = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  Keyword = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  Label = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  Number = {
    bg = "NONE",
    bold = true,
    ctermbg = "NONE",
    ctermfg = 141,
    fg = "#d56af5",
  },
  Operator = {
    bg = "NONE",
    bold = true,
    ctermbg = "NONE",
    ctermfg = 185,
    fg = "#E6DB74",
    sp = "none",
  },
  Special = {
    bg = "NONE",
    bold = true,
    ctermbg = "NONE",
    ctermfg = 13,
    fg = "#FF00FF",
  },
  SpecialChar = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  Statement = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  StorageClass = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  String = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
  },
  Structure = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  Tag = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 197,
    fg = "#F92782",
  },
  Todo = {
    bg = "#111111",
    bold = true,
    ctermbg = 233,
    ctermfg = 15,
    fg = "#F8F8F2",
  },
  Type = {
    bg = "NONE",
    ctermbg = "NONE",
    ctermfg = 81,
    fg = "#66D9EF",
    sp = "none",
  },
}
