return {
  Pmenu = {
    fg = "#F8F8F8",
    bg = "#223344",
    ctermfg = 15,
    ctermbg = 23,
  },
  PmenuSet = {
    fg = "#66D9EF",
    bg = "#000000",
    ctermfg = 81,
    ctermbg = 233,
  },
  PmenuSBar = {
    fg = "#66D9EF",
    bg = "#334455",
    ctermfg = 81,
    ctermbg = 59,
  },
  PmenuSel = {
    fg = "#66D9EF",
    bg = "#334455",
    ctermfg = 81,
    ctermbg = 59,
  },
  PmenuThumb = {
    fg = "#778899",
    bg = "#778899",
    ctermfg = 103,
    ctermbg = 103,
  },
  Normal = {
    fg = "#F8F8F2",
    bg = "#000000",
    ctermfg = 15,
    ctermbg = 233,
  },
  Conceal = {
    fg = "#66D9EF",
    bg = "#000000",
    ctermfg = 81,
    ctermbg = 233,
  },
  NonText = {
    fg = "#49483E",
    bg = "NONE",
    ctermfg = 59,
    ctermbg = "NONE",
  },
  -- StatusLine = {
  --    fg = "#66D9EF",
  --    bg = "#000000",
  --    ctermfg = 81,
  --    ctermbg = 233,
  -- },
  -- StatusLineNC = {
  --    fg = "#178899",
  --    bg = "#000000",
  --    ctermfg = 103,
  --    ctermbg = 233,
  -- },
  Search = {
    fg = "#000000",
    bg = "#FFE972",
    ctermfg = 00,
    ctermbg = 221,
  },
  VertSplit = {
    fg = "#75715E",
    bg = "NONE",
    ctermfg = 95,
    ctermbg = "NONE",
  },
  LineNr = {
    fg = "#8F908A",
    bg = "NONE",
    ctermfg = 102,
    ctermbg = "NONE",
  },
  SignColumn = {
    fg = "NONE",
    bg = "#211F1C",
    ctermfg = "NONE",
    ctermbg = 00,
  },
  Question = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  ModeMsg = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  MoreMsg = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  ErrorMsg = {
    fg = "#000000",
    bg = "#F92672",
    ctermfg = 233,
    ctermbg = 197,
  },
  WarningMsg = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  TabLine = {
    fg = "#8F908A",
    bg = "#000000",
    ctermfg = 102,
    ctermbg = 233,
  },
  TabLineSel = {
    fg = "#F8F8F2",
    bg = "#334455",
    ctermfg = 15,
    ctermbg = 59,
  },
  TabLineFill = {
    fg = "#000000",
    bg = "#111111",
    ctermfg = 233,
    ctermbg = 233,
  },
  SpecialKey = {
    fg = "#E6DB74",
    -- fg = "#49483E",
    bg = "NONE",
    ctermfg = 59,
    ctermbg = "NONE",
  },
  Title = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  Directory = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  DiffAdd = {
    fg = "#F8F8F8",
    bg = "#253B22",
    ctermfg = 15,
    ctermbg = 22,
  },
  DiffDelete = {
    fg = "#F92672",
    bg = "#420E09",
    ctermfg = 197,
    ctermbg = 52,
  },
  DiffChange = {
    fg = "#E6DB74",
    bg = "#420E09",
    ctermfg = 185,
    ctermbg = 52,
  },
  DiffText = {
    fg = "#75715E",
    bg = "NONE",
    ctermfg = 95,
    ctermbg = "NONE",
  },
  Folded = {
    fg = "#778899",
    bg = "#211F1C",
    ctermfg = 103,
    ctermbg = 00,
  },
  FoldColumn = {
    fg = "NONE",
    bg = "#211F1C",
    ctermfg = "NONE",
    ctermbg = 00,
  },
  ColorColumn = {
    fg = "NONE",
    bg = "#383A3E",
    ctermfg = "NONE",
    ctermbg = 236,
  },
  CursorColumn = {
    fg = "NONE",
    bg = "#383A3E",
    ctermfg = "NONE",
    ctermbg = 236,
  },
  CursorLine = {
    fg = "NONE",
    bg = "#383A3E",
    ctermfg = "NONE",
    ctermbg = 236,
  },
  Cursor = {
    fg = "#000000",
    bg = "#F8F8F2",
    ctermfg = 233,
    ctermbg = 15,
  },
  Visual = {
    fg = "NONE",
    bg = "#49483E",
    ctermfg = "NONE",
    ctermbg = 59,
  },
  MatchParen = {
    fg = "#000000",
    bg = "#FD971F",
    ctermfg = 208,
    ctermbg = "NONE",
    bold = true,
  },
  CmpBorder = {
    fg = "#115064",
    bg = "NONE",
  },
  CmpDocBorder = {
    fg = "#115064",
    bg = "NONE",
  },
  Constant = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  Number = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
    bold = true,
  },
  Float = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  Boolean = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  Character = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  String = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  Type = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  Structure = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  StorageClass = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  TypeDef = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  Identifier = {
    fg = "#ca2168",
    bg = "NONE",
    bold = true,
    ctermfg = 197,
    ctermbg = "NONE",
  },
  Function = {
    fg = "#A6E22E",
    bg = "NONE",
    bold = true,
    ctermfg = 112,
    ctermbg = "NONE",
  },
  Statement = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  Operator = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
    bold = true,
  },
  Label = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  Keyword = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  Preproc = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  Include = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  Define = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  Macro = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  PreCondit = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  Special = {
    fg = "#FF00FF",
    bg = "NONE",
    ctermfg = 13,
    ctermbg = "NONE",
    bold = true,
  },
  SpecialChar = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  Delimiter = {
    fg = "#F92782",
    bg = "NONE",
    bold = true,
    ctermfg = 197,
    ctermbg = "NONE",
  },
  Comment = {
    fg = "#5F87AF",
    bg = "NONE",
    italic = true,
    ctermfg = 67,
    ctermbg = "NONE",
  },
  SpecialComment = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  Tag = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  Underlined = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  Ignore = {
    fg = "NONE",
    bg = "NONE",
    ctermfg = "NONE",
    ctermbg = "NONE",
  },
  Todo = {
    fg = "#F8F8F2",
    bg = "#111111",
    bold = true,
    ctermfg = 15,
    ctermbg = 233,
  },
  Error = {
    fg = "#F8F8F2",
    bg = "#960020",
    ctermfg = 15,
    ctermbg = 88,
  },
  cppSTLnamespace = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  cppSTLtype = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  cppModifier = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsStorageClass = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsOperator = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsBooleanTrue = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  jsBooleanFalse = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  jsModules = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsModuleWords = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsOf = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsArgsObj = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsImportContainer = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsExportContainer = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsCommentTodo = {
    fg = "#778899",
    bg = "NONE",
    ctermfg = 103,
    ctermbg = "NONE",
  },
  jsLineComment = {
    fg = "#5F87AF",
    bg = "NONE",
    italic = true,
    ctermfg = 67,
    ctermbg = "NONE",
  },
  jsEnvComment = {
    fg = "#5F87AF",
    bg = "NONE",
    italic = true,
    ctermfg = 67,
    ctermbg = "NONE",
  },
  jsCvsTag = {
    fg = "#5F87AF",
    bg = "NONE",
    italic = true,
    ctermfg = 67,
    ctermbg = "NONE",
  },
  jsComment = {
    fg = "#5F87AF",
    bg = "NONE",
    italic = true,
    ctermfg = 67,
    ctermbg = "NONE",
  },
  jsBlockComment = {
    fg = "#5F87AF",
    bg = "NONE",
    italic = true,
    ctermfg = 67,
    ctermbg = "NONE",
  },
  jsDocTags = {
    fg = "#778899",
    bg = "NONE",
    ctermfg = 103,
    ctermbg = "NONE",
  },
  jsDocType = {
    fg = "#778899",
    bg = "NONE",
    ctermfg = 103,
    ctermbg = "NONE",
  },
  jsDocTypeNoParam = {
    fg = "#778899",
    bg = "NONE",
    ctermfg = 103,
    ctermbg = "NONE",
  },
  jsDocParam = {
    fg = "#778899",
    bg = "NONE",
    ctermfg = 103,
    ctermbg = "NONE",
  },
  jsDocSeeTag = {
    fg = "#778899",
    bg = "NONE",
    ctermfg = 103,
    ctermbg = "NONE",
  },
  jsTemplateVar = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsStringD = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsStringS = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsTemplateString = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsTemplateBraces = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  jsTaggedTemplate = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpCharClass = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpBoundary = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpBackRef = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpQuantifier = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpOr = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpMod = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpSpecial = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpGroup = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsRegexpString = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsNumber = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  jsFloat = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  jsObjectKey = {
    fg = "#E6DB74",
    bg = "NONE",
    ctermfg = 185,
    ctermbg = "NONE",
  },
  jsFunctionKey = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  jsDecorator = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  jsDecoratorFunction = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  jsStatement = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsConditional = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsRepeat = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsLabel = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsKeyword = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsClass = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsAsyncKeyword = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsGlobalObjects = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsGlobalNodeObjects = {
    fg = "#66D9EF",
    bg = "NONE",
    italic = true,
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsThis = {
    fg = "#66D9EF",
    bg = "NONE",
    italic = true,
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsExceptions = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsBuiltins = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsFutureKeys = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsHtmlEvents = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsTernaryIfOperator = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsGenerator = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsFuncName = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  jsFuncArgs = {
    fg = "#FD971F",
    bg = "NONE",
    ctermfg = 208,
    ctermbg = "NONE",
  },
  jsFuncArgRest = {
    fg = "#F92672",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  jsArrowFunction = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsFuncCall = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  javaScriptMethodCallWithoutArgs = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  javaScriptMethodCallWithArgs = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  javaScriptStaticFunctionWithArgs = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  javaScriptStaticFunctionWithoutArgs = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  javaScriptFunctionCallWithArgs = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  javaScriptFunctionCallWithoutArgs = {
    fg = "#A6E22E",
    bg = "NONE",
    ctermfg = 112,
    ctermbg = "NONE",
  },
  javaScriptArrowFunction = {
    fg = "#66D9EF",
    bg = "NONE",
    ctermfg = 81,
    ctermbg = "NONE",
  },
  jsonNull = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  jsonKeyword = {
    fg = "#F8F8F2",
    bg = "NONE",
    ctermfg = 15,
    ctermbg = "NONE",
  },
  jsonPadding = {
    fg = "#F8F8F2",
    bg = "NONE",
    ctermfg = 15,
    ctermbg = "NONE",
  },
  jsonBraces = {
    fg = "#F8F8F2",
    bg = "NONE",
    ctermfg = 15,
    ctermbg = "NONE",
  },
  purescriptImportKeyword = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  purescriptConstructor = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  purescriptConstructorDecl = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  purescriptTypeAlias = {
    fg = "#d56af5",
    bg = "NONE",
    ctermfg = 141,
    ctermbg = "NONE",
  },
  purescriptModuleKeyword = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  purescriptWhere = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  purescriptData = {
    fg = "#F92782",
    bg = "NONE",
    ctermfg = 197,
    ctermbg = "NONE",
  },
  purescriptTypeVar = {
    fg = "#F8F8F2",
    bg = "NONE",
    ctermfg = 15,
    ctermbg = "NONE",
  },
  purescriptDelimiter = {
    fg = "#F8F8F2",
    bg = "NONE",
    ctermfg = 15,
    ctermbg = "NONE",
  },
  TermCursor = {
    fg = "#000000",
    bg = "#F8F8F2",
    ctermfg = 233,
    ctermbg = 15,
  },
  TermCursorNC = {
    fg = "#000000",
    bg = "#778899",
    ctermfg = 233,
    ctermbg = 103,
  },
}
